# %%
import os
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
# %%
import kagglehub

data_path = kagglehub.dataset_download("khyeh0719/ptb-xl-dataset")

print("Path to dataset files:", data_path)
# %%
import pandas as pd
import numpy as np
import wfdb
import ast

def load_raw_data(df, sampling_rate, path):
    if sampling_rate == 100:
        data = [wfdb.rdsamp(path+f) for f in df.filename_lr]
    else:
        data = [wfdb.rdsamp(path+f) for f in df.filename_hr]
    data = np.array([signal for signal, meta in data])
    return data

path = data_path + '/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/'
sampling_rate=100

# load and convert annotation data
Y = pd.read_csv(path+'ptbxl_database.csv', index_col='ecg_id')
Y.scp_codes = Y.scp_codes.apply(lambda x: ast.literal_eval(x))


# Load raw signal data
X = load_raw_data(Y, sampling_rate, path)

# %%
X = X[:,:,:6]
X.shape

# %%
X
# %%

# Load scp_statements.csv for diagnostic aggregation
agg_df = pd.read_csv(path+'scp_statements.csv', index_col=0)
agg_df = agg_df[agg_df.diagnostic == 1]
print(agg_df.shape)
agg_df.head()
# %%

def aggregate_diagnostic(y_dic):
    tmp = []
    for key in y_dic.keys():
        if key in agg_df.index:
            tmp.append(agg_df.loc[key].diagnostic_class)
    return list(set(tmp))

# Apply diagnostic superclass
Y['diagnostic_superclass'] = Y.scp_codes.apply(aggregate_diagnostic)

# %%
def safe_literal_eval(val):
    if isinstance(val, str):
        try:
            return ast.literal_eval(val)
        except (ValueError, SyntaxError):
            return []  # или верни val, если хочешь оставить как есть
    elif isinstance(val, list):
        return val  # уже список — ничего не делаем
    else:
        return []  # на случай NaN или None

# Применяем безопасное преобразование
Y['diagnostic_superclass'] = Y['diagnostic_superclass'].apply(safe_literal_eval)

# Теперь фильтрация
allowed_classes = {'NORM', 'CD', 'ARRHYTHMIA'}
Y = Y[Y['diagnostic_superclass'].apply(
    lambda diag_list: isinstance(diag_list, list) and all(d in allowed_classes for d in diag_list)
)].reset_index(drop=True)

print(f"Осталось записей: {len(Y)}")

# %%
# print(Y.scp_codes)

def aggregate_subclass_diagnostic(y_dic):
    allowed_superclasses = {'NORM', 'CD', 'ARRHYTHMIA'}
    tmp = []
    for key in y_dic.keys():
        if key in agg_df.index:
            supercls = agg_df.loc[key]['diagnostic_class']
            if supercls in allowed_superclasses:
                tmp.append(agg_df.loc[key]['diagnostic_subclass'])
    ret = list(set(tmp))  # убираем дубликаты
    ret = ['sub_' + r for r in ret]  # префикс для отличия от суперклассов
    return ret
# Apply diagnostic subclass
Y['diagnostic_subclass'] = Y.scp_codes.apply(aggregate_subclass_diagnostic)

# %%
import missingno as msno

msno.matrix(Y)
plt.show()

# %%

# Заполнение пропусков в числовых признаках
Y['age'].fillna(0, inplace=True)
Y['sex'].fillna(0, inplace=True)
Y['height'].fillna(0, inplace=True)
Y['weight'].fillna(0, inplace=True)

# Исправление аномальных значений роста (< 50 см — явно ошибка)
Y.loc[Y['height'] < 50, 'height'] = np.nan
Y['height'].fillna(0, inplace=True)

# Кодирование стадии инфаркта 1
Y['infarction_stadium1'] = Y['infarction_stadium1'].replace({
    'unknown': 0,
    'Stadium I': 1,
    'Stadium I-II': 2,
    'Stadium II': 3,
    'Stadium II-III': 4,
    'Stadium III': 5
}).fillna(0).astype(int)

# Кодирование стадии инфаркта 2
Y['infarction_stadium2'] = Y['infarction_stadium2'].replace({
    'unknown': 0,
    'Stadium I': 1,
    'Stadium II': 2,
    'Stadium III': 3
}).fillna(0).astype(int)

# Бинарный признак наличия кардиостимулятора
Y['pacemaker'] = (Y['pacemaker'] == 'ja, pacemaker').astype(float)

# %%
# Столбцы, которые НЕ нужны для твоей задачи
columns_to_drop = [
    'infarction_stadium1',
    'infarction_stadium2',
    'nurse',
    'site',
    'device',
    'recording_date',
    'report',
    'validated_by',
    'second_opinion',
    'initial_autogenerated_report',
    'validated_by_human',
    'baseline_drift',
    'static_noise',
    'burst_noise',
    'electrodes_problems',
    'extra_beats'
]

# Удаляем их (если есть)
Y = Y.drop(columns=[col for col in columns_to_drop if col in Y.columns])

# Проверка
print("Осталось столбцов:", len(Y.columns))
print(Y.columns.tolist())

# %%
# === ПРЕДОБРАБОТКА СИГНАЛОВ: ФИЛЬТРАЦИЯ + СТАНДАРТИЗАЦИЯ ===
from scipy import signal

def preprocess_ecg_batch(X, fs=100):
    # Bandpass 0.5–40 Hz
    sos = signal.butter(4, [0.5, 40], btype='band', fs=fs, output='sos')
    X = signal.sosfilt(sos, X, axis=1)
    # Z-score по каждому отведению
    X = (X - X.mean(axis=1, keepdims=True)) / (X.std(axis=1, keepdims=True) + 1e-6)
    return X

print("Предобработка сигналов...")
X = preprocess_ecg_batch(X, fs=sampling_rate)
print("✅ Сигналы отфильтрованы и стандартизированы.")
# %%
original_index = Y.index.copy()

X = X[original_index]

# %%
# Подготовка контейнеров для сбора уникальных ключей и значений
all_keys = set()
all_values = set()

# Проходим по каждой строке (каждому объекту)
for row in Y['scp_codes']:
    # Добавляем все ключи из текущего объекта
    all_keys.update(row.keys())
    
    # Добавляем все значения из текущего объекта
    all_values.update(row.values())

# Печать уникальных ключей и значений
print("Уникальные ключи:", *sorted(all_keys))
print("Уникальные значения:", *sorted(all_values))

# %%
valid_scp_codes = {
    # Ритмы
    'SR', 'AFIB', 'AFLT', 'PAC', 'PVC', 'SVTAC', 'SARRH', 'SBRAD', 'STACH',
    # Блокады и нарушения проводимости
    '1AVB', '2AVB', '3AVB', 
    'CRBBB', 'CLBBB', 'IRBBB', 'ILBBB',
    'LAFB', 'LPFB',
    # Синдромы и паттерны
    'WPW', 'BIGU', 'TRIGU',
    # Норма
    'NORM'
}

# === ШАГ 2: Фильтрация записей ===
# Оставляем только те, у которых ВСЕ коды ∈ valid_scp_codes
def is_valid_record(scp_dict):
    return all(code in valid_scp_codes for code in scp_dict.keys())

mask_valid = Y['scp_codes'].apply(is_valid_record)
Y = Y[mask_valid].reset_index(drop=True)

print(f"✅ Осталось записей после фильтрации: {len(Y)}")

# %%
# === ШАГ 3: Выбираем ТОЛЬКО те диагнозы, которые будем предсказывать ИИ ===
# (исключаем SBRAD/STACH — они выводятся из SR + ЧСС)
ii_targets = {
    'is_sinus_rhythm': 'SR',
    'is_afib': 'AFIB',
    'is_aflt': 'AFLT',
    'is_pac': 'PAC',
    'is_pvc': 'PVC',
    'is_svt': 'SVTAC',
    'is_sinus_arrhythmia': 'SARRH',
    'has_1avb': '1AVB',
    'has_2avb': '2AVB',
    'has_3avb': '3AVB',
    'has_rbbb': 'CRBBB',      # complete RBBB
    'has_lbbb': 'CLBBB',      # complete LBBB
    'has_irbbb': 'IRBBB',     # incomplete RBBB
    'has_ilbbb': 'ILBBB',     # incomplete LBBB
    'has_lafb': 'LAFB',
    'has_lpfb': 'LPFB',
    'has_wpw': 'WPW',
    'has_bigeminy': 'BIGU',
    'has_trigeminy': 'TRIGU'
}

# Создаём бинарные метки
for col_name, scp_code in ii_targets.items():
    Y[col_name] = Y['scp_codes'].apply(lambda x: 1 if scp_code in x else 0)

target_cols = list(ii_targets.keys())
print(f"🎯 Целевые переменные для ИИ ({len(target_cols)} шт.):")
print(target_cols)

# %%

# === ШАГ 4: Отфильтруй X по тем же индексам, что и Y ===
# (делай это ПОСЛЕ фильтрации Y, но ДО загрузки X, если возможно)
# Если X уже загружен для полного Y — сделай так:
X = X[Y.index]  # ← ЭТО ОБЯЗАТЕЛЬНО!

# === ШАГ 5: Разделение на train/test с помощью strat_fold ===
test_fold = 10
test_mask = (Y['strat_fold'] == test_fold)
train_mask = ~test_mask

# Сигналы (уже предобработанные: фильтрация + нормализация)
X_train = X[train_mask]  # shape: (N_train, 1000, 6)
X_test = X[test_mask]    # shape: (N_test, 1000, 6)

# Целевые переменные для ИИ (мультилейбл)
y_train = Y.loc[train_mask, target_cols].values.astype(np.float32)  # shape: (N_train, num_targets)
y_test = Y.loc[test_mask, target_cols].values.astype(np.float32)    # shape: (N_test, num_targets)

print(f"\n✅ Готово!")
print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_test:  {X_test.shape},  y_test:  {y_test.shape}")

# === ШАГ 6: Проверка баланса (опционально) ===
print("\n📊 Баланс классов в train:")
for i, col in enumerate(target_cols):
    pos = y_train[:, i].sum()
    total = len(y_train)
    print(f"{col}: {int(pos)} / {total} ({pos/total:.1%})")
# %%
# Split data into train and test
# test_fold = 10
# # Train
# X_train = X[np.where(Y.strat_fold != test_fold)]
# y_train = Y[(Y.strat_fold != test_fold)].diagnostic_superclass
# # Test
# X_test = X[np.where(Y.strat_fold == test_fold)]
# y_test = Y[Y.strat_fold == test_fold].diagnostic_superclass

# %%
import os
import numpy as np
import pandas as pd

# Создаём папку для данных (если не существует)
output_dir = 'ecg_data'
os.makedirs(output_dir, exist_ok=True)

# === 1. Сохраняем сигналы и мультилейбл-метки ИИ ===
np.save(os.path.join(output_dir, 'X_train.npy'), X_train)
np.save(os.path.join(output_dir, 'X_test.npy'), X_test)
np.save(os.path.join(output_dir, 'y_train.npy'), y_train)
np.save(os.path.join(output_dir, 'y_test.npy'), y_test)

# === 2. Сохраняем метаданные (для анализа и отладки) ===
Y_train_meta = Y[train_mask].copy()
Y_test_meta = Y[test_mask].copy()

Y_train_meta.to_csv(os.path.join(output_dir, 'Y_train.csv'), index=True)
Y_test_meta.to_csv(os.path.join(output_dir, 'Y_test.csv'), index=True)

# === 3. Сохраняем список целевых переменных (чтобы не забыть порядок) ===
with open(os.path.join(output_dir, 'target_columns.txt'), 'w') as f:
    for col in target_cols:
        f.write(col + '\n')

print(f"✅ Все данные сохранены в папку: '{output_dir}'")
print(f"   - Сигналы: X_train.npy, X_test.npy")
print(f"   - Метки ИИ: y_train.npy, y_test.npy")
print(f"   - Метаданные: Y_train.csv, Y_test.csv")
print(f"   - Целевые столбцы: target_columns.txt")

# %%
